hexlet_django_blog/articles/urls.py
from django.urls import path
from hexlet_django_blog.articles import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='articles_index'),
    path('<int:id>/edit/', views.ArticleFormEditView.as_view(), name='articles_update'),
    path('<int:id>/delete/', views.ArticleFormDestroyView.as_view(), name='articles_destroy'),
    path('<int:id>', views.ArticleView.as_view(), name='articles_detail'),
    path('create/', views.ArticleFormCreateView.as_view(), name='articles_create'),
]

hexlet_django_blog/categories/urls.py
from django.urls import path
from hexlet_django_blog.categories import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='categories_index'),
    path(
        '<int:id>/update/',
        views.CategoryUpdateView.as_view(),
        name='category_update'
    ),
    path('<int:id>/', views.CategoryView.as_view(), name='categories_detail'),

    path(
        'create/',
        views.CategoryFormCreateView.as_view(),
        name='category_create'
    )
]

hexlet_django_blog/urls.py
from django.urls import include, path
from hexlet_django_blog import views
from django.contrib import admin


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('articles/', include('hexlet_django_blog.articles.urls')),
    path('categories/', include('hexlet_django_blog.categories.urls')),
    path('admin/', admin.site.urls),
]

hexlet_django_blog/Clips/models.py
from django.db import models
from django.db.models import Avg, Max, Min, Count

class Clip(models.Model):
    title = models.CharField(max_length=200)

    def like(self):
        # на основе экземпляра класса Clip создаётся новая запись в таблице класса Cliplike/ClipDislike
        # в таблицу заносятся титул и id экземпляра класса 
        # на основе титула и id в последствии можно делать выборку 
        ClipLike.objects.create(clip=self)

    def dislike(self):
        ClipDislike.objects.create(clip=self)

    @classmethod
    def rates_for(cls, **kwargs) -> (int, int):
        """
        Returns a tuple of integers (likes, dislikes)
        for the clip(s) filtered by provided kwargs.
        """
# в cls (классе Clip) содержаться все его экземпляры класса. Мы ищем этот экземпляр через фильтр и аннотируем его 
# по количеству случаев он был добавлен в таблицу Cliplike или ClipDislike

        likeclips = cls.objects.filter(
            **kwargs).annotate(num_cliplike=Count(
                "cliplike", distinct=True))
        dislikeclips = cls.objects.filter(
            **kwargs).annotate(num_clipdislike=Count(
                "clipdislike", distinct=True))
        return likeclips[0].num_cliplike, dislikeclips[0].num_clipdislike


class ClipLike(models.Model):
    clip = models.ForeignKey(Clip, on_delete=models.CASCADE)


class ClipDislike(models.Model):  # на основе экземпляра класса Clip создаётся новая запись в таблице класса Cliplike/ClipDislike
    clip = models.ForeignKey(Clip, on_delete=models.CASCADE)

hexlet_django_blog/articles/models.py
from django.db import models
from django.utils import timezone
from hexlet_django_blog.categories.models import Category


# Create your models here.
class Article(models.Model):
    title = models.CharField('title', max_length=255)
    body = models.CharField('body', max_length=1000)
    created_at = models.DateField('created_at', default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    def __str__(self):
        """Represent model object."""
        return self.title

hexlet_django_blog/categories/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    STATE_TYPE = (
        ('draft', 'draft'),
        ('published', 'published')
    )
    name = models.CharField('name', max_length=255)
    description = models.CharField('description', max_length=255)
    state = models.CharField(choices=STATE_TYPE, max_length=9, default='draft')

    def __str__(self):
        """Represent model object."""
        return self.name

hexlet_django_blog/islands/models.py
from django.db import models


class Island(models.Model):
    name = models.CharField(max_length=200)

    def can_reach(self, island, *, by_ship):
        # "Return True if one can reach the @island using a @by ship"
        main = self.ships.first()
        secondary = island.ships.first()
        return by_ship.name == main.name and by_ship.name == secondary.name


class Ship(models.Model):
    name = models.CharField(max_length=200)
    islands = models.ManyToManyField(Island, related_name='ships')

hexlet_django_blog/projects/models.py
from django.db import models, transaction


class Project(models.Model):
    name = models.CharField(max_length=200)


    @classmethod
    def reorganize(cls, assignments):
        # BEGIN (write your solution here)
        with transaction.atomic():
            for worker_id, project_id in assignments.items():
                Worker.objects.filter(id=worker_id).update(project=project_id)

            Worker.objects.exclude(id__in=assignments).update(project=None)
        # END


class Worker(models.Model):
    name = models.CharField(max_length=200)
    project = models.ForeignKey(
        Project,
        null=True,
        on_delete=models.SET_NULL,
    )

hexlet_django_blog/articles/forms.py
from django.forms import ModelForm
from .models import Article

# Форма описывает поля существующей модели Article. Поэтому для описания формы
# воспользуемся вспомогательным классом ModelForm, чтобы создать Form-класс из
# модели Django:
class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'body', 'category']

hexlet_django_blog/categories/forms.py
from django.forms import ModelForm
from django import forms
from hexlet_django_blog.categories.models import Category


class CategoryForm(forms.ModelForm):  # переопределяем модель
    name = forms.CharField(max_length=100, required=True)
    description = forms.CharField(max_length=200, required=True)

    class Meta:
        model = Category
        fields = ['name', 'description', 'state']

hexlet_django_blog/articles/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from hexlet_django_blog.articles.models import Article
from django.db.models import Q
from hexlet_django_blog.articles.forms import ArticleForm
from django.contrib import messages
# в любом случае работает фильтрация
# если не пользуешься формой, то фильтруешь все статьи которые содержат
# пустую строку "". А пустую строку содержит любая строка поэтому фильтр
# возвращает из БД все.
class IndexView(View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get('q', '')  # извлечение запроса из формы: "Get the value of a GET variable with name
        # 'q', and if it doesn't exist, return ''.
        articles = Article.objects.filter(Q(title__icontains=query))  # поиск в названиях статей в соответсвии с
        # запросом
        return render(request, 'articles/index.html', context={
            'articles': articles,
            'query': query,
        })


class ArticleView(View):
    template_name = 'articles/article.html'

    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, id=kwargs['id'])
        return render(request, self.template_name, context={
            'article': article,
        })

# В данном get-обработчике мы создаем объект формы и передаем его в шаблон:
class ArticleFormCreateView(View):

    def get(self, request, *args, **kwargs):
        form = ArticleForm()
        return render(request, 'articles/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = ArticleForm(request.POST)
        if form.is_valid():  # Если данные корректные, то сохраняем данные формы
            form.save()
            messages.success(request, "Статья добавлена")
            return redirect('/articles/')  # Редирект на указанный маршрут
        # Если данные некоректные, то возвращем человека обратно на страницу с заполенной формой
        messages.error(request, 'Статья неверна. Попробуйте снова')
        return render(request, 'articles/create.html', {'form': form})


class ArticleFormEditView(View):

    def get(self, request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = Article.objects.get(id=article_id)
        form = ArticleForm(instance=article)
        return render(request, 'articles/update.html', {'form': form, 'article_id':article_id})

    def post(self, request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = Article.objects.get(id=article_id)
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles_index')
        return render(request, 'articles/update.html', {'form': form, 'article_id': article_id})


class ArticleFormDestroyView(View):
    def post(self, request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = Article.objects.get(id=article_id)
        if article:
            article.delete()
        return redirect('articles_index')

hexlet_django_blog/categories/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from hexlet_django_blog.categories.models import Category
from hexlet_django_blog.categories.forms import CategoryForm


class IndexView(View):
    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        return render(request, 'categories/index.html', context={
            'categories': categories,
        })


# Создайте вью, которая извлекает из базы текущую запрошенную категорию и передает ее в шаблон. Task 13
# Не забудьте подключить вью в categories/urls.py.
class CategoryView(View):
    template_name = 'categories/category.html'

    def get(self, request, *args, **kwargs):
        category = get_object_or_404(Category, id=kwargs['id'])
        return render(request, self.template_name, context={
            'category': category,
        })


class CategoryFormCreateView(View):

    def get(self, request, *args, **kwargs):
        form = CategoryForm()
        return render(request, 'categories/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('categories_index')
        
        return render(request, 'categories/create.html', {'form': form})


class CategoryUpdateView(View):

    def get(self, request, *args, **kwargs):
        category_id = kwargs.get('id')
        category = Category.objects.get(id=category_id)
        form = CategoryForm(instance=category)
        return render(request, 'categories/update.html', {
            'form': form,
            'category_id': category_id
            }
        )

    def post(self, request, *args, **kwargs):
        category_id = kwargs.get('id')
        category = Category.objects.get(id=category_id)
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('categories_index')

        return render(request, 'categories/update.html', {
            'form': form,
            'category_id': category_id
            }
        )

hexlet_django_blog/projects/views.py
from django.shortcuts import render

# Create your views here.

hexlet_django_blog/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

hexlet_django_blog/templates/categories/category.html
{% extends 'layout.html' %}
{% load bootstrap4 i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}
<div class="container mt-4">
<!--   ссылка на создание новой ктегории -->
  <small><a href="{% url 'category_create' %}">Создать категорию</a></small>
  
<!-- Вывод имени и описание категории. Вывод списка названий статей и категории в виде <ol> списка. 
  Если статей в категории нет, то тег <ol> не отображается. Каждое название – ссылка на саму статью. -->
  
  <h1>{{ category.name }}</h1>
  <div>{{ category.description }}</div>
  {% if category.article_set.all %}
  <h2>Статьи</h2>
  <ol>
    {% for article in category.article_set.all %}
    <li>
      <a href="{% url 'articles_detail' article.id %}">{{ article.title }}</a>
    </li>
    {% endfor %}
  </ol>
  {% endif %}
{% endblock content %}

hexlet_django_blog/templates/categories/create.html
{% extends 'layout.html' %}
{% load bootstrap4 i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}
<!-- показ ошибок при их наличии -->
{% if form.subject.errors %}
  <div>
    <ul>
    {% for error in form.subject.errors %}
      <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ul>
  </div>
  {% endif %}
<!-- форма создания категории -->
  <form action="{% url 'category_create' %}" method="post">
    {% csrf_token %}
    <table border="1">
      {{ form }}
    </table>
    <input type="submit" value="Создать">
  </form>
{% endblock content %}

hexlet_django_blog/templates/categories/index.html
{% extends 'layout.html' %}
{% load bootstrap4 i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}
  <div class="container mt-4">
    
<!--   ссылка на страницу создания категории -->
    
    <small><a href="{% url 'category_create' %}">Создать категорию</a></small>
  <h1>Список категорий статей</h1>
  {% for category in categories %}
    
<!--     ссылка на определённую категорию через определитель id  -->
    
    <h2><a class="link" href="{% url 'categories_detail' category.id %}">
      {{ category.name }}</a>
    </h2>
    <div>{{ category.description }}</div>
    
<!-- ссылка на изменение категории -->
    
    <a href="{% url 'category_update' category.id %}">Редактировать</a>
  {% endfor %}
  </div>
{% endblock content %}

hexlet_django_blog/templates/categories/update.html
{% extends 'layout.html' %}
{% load bootstrap4 i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}
  <div class="container mt-4">
    {% if form.subject.errors %}
    <div>    
      <ul>
      {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
      {% endfor %}
      </ul>
    </div>
    {% endif %}
  <form action="{% url 'category_update' id=category_id %}" method="post">
    {% csrf_token %}
    <table border="1">
      {{ form }}
    </table>
    <input type="submit" value="Сохранить">
  </form>
{% endblock %}